Repository Aarhus-Psychiatry-Research/psycop-common, pull requests merged in 2023-11, with the labels that each got.

#310 feat: add smoking and hypertension
  psycop/projects/cvd/feature_generation/feature_layeres/layer_1.py
Labels: Stale

#267 ci - update cruft
  .cruft.json
  .github/recommended_repo_setup.md
  .github/workflows/cruft.yml
  .github/workflows/release.yml
Labels: dependencies

#357 Adding filtering to train
  psycop/common/data_structures/temporal_event.py
  psycop/common/sequence_models/config_schema.py
  psycop/common/sequence_models/config_utils.py
  psycop/common/sequence_models/dataset.py
  psycop/common/sequence_models/embedders/BEHRT_embedders.py
  psycop/common/sequence_models/tests/test_embedding.py
  psycop/common/sequence_models/tests/test_train.py
  psycop/common/sequence_models/tests/utils.py
  psycop/common/sequence_models/train.py
  psycop/projects/sequence_models/datasets.py
  psycop/projects/sequence_models/fine_tune.py
  psycop/projects/sequence_models/paper.md
  psycop/projects/sequence_models/pretrain.py
  psycop/projects/sequence_models/pretrain_behrt.cfg
  psycop/projects/sequence_models/pretrain_mini_behrt.cfg
Labels: Stale

#434 dev: update requirements to avoid snyk vulnerabilities
  .snyk
  Dockerfile
  dev-requirements.txt
  gpu-requirements.txt
  requirements.txt
  tasks.py
Labels: waiting-for-external

#459 dev: add pytest testmon
  test-requirements.txt
Labels: waiting-for-external
